application: aries-auto
version: 1
runtime: go
api_version: go1

skip_files:
- ^node_modules/.*
- ^.tmp/.*
- ^gulp/.*
- ^e2e/.*
- ^src/.*
- ^(.*/)?package\.json
- ^(.*/)?gulpfile\.js
- ^(.*/)?app\.yaml
- ^(.*/)?bower\.json
- ^(.*/)?karma\.conf\.js
- ^(.*/)?protractor\.conf\.js

handlers:
- url: /scripts
  static_dir: dist/scripts
- url: /fonts
  static_dir: dist/fonts
  mime_type: application/x-font-otf
- url: /lib
  static_dir: dist/lib
- url: /assets
  static_dir: dist/assets
- url: /styles
  static_dir: dist/styles
- url: /views
  static_dir: dist/views
- url: /.*
  script: _go_app