application: aries-auto
version: 9
runtime: go
api_version: go1

skip_files:
- ^node_modules/.*
- ^.tmp/.*
- ^gulp/.*
- ^e2e/.*
- ^src/.*
- ^(.*/)?package\.json
- ^(.*/)?gulpfile\.js
- ^(.*/)?app\.yaml
- ^(.*/)?bower\.json
- ^(.*/)?karma\.conf\.js
- ^(.*/)?protractor\.conf\.js

handlers:
- url: /scripts
  static_dir: dist/scripts
- url: /fonts
  static_dir: dist/fonts
  mime_type: application/x-font-otf
- url: /lib
  static_dir: dist/lib
- url: /assets
  static_dir: dist/assets
- url: /styles
  static_dir: dist/styles
- url: /views
  static_dir: dist/views
- url: /(.*\.(xml))$
  static_files: dist/\1
  upload: dist/.*\.(xml)$
- url: /google73134e511c5bcd8d.html
  static_files: dist/google73134e511c5bcd8d.html
  upload: dist/google73134e511c5bcd8d.html
- url: /.*
  script: _go_app

env_variables:
  PRERENDER_TOKEN: 'Ny5UurBwp9vvWl0TqFmz'
