runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 4
  cool_down_period_sec: 120 # default value

env_variables:
  NODE_ENV: 'production'
  API_KEY: '9300f7bc-2ca6-11e4-8758-42010af0fd79'

skip_files:
  - ^(.*/)?.*/node_modules/.*$
