
module.exports.fields = [
	{
		type: 'text',
		label: 'Enter your first name:',
		placeholder: 'Enter your first name.',
		name: 'firstName',
		width: '6',
		required: true,
	},
	{
		type: 'text',
		label: 'Enter your last name:',
		placeholder: 'Enter your last name.',
		name: 'lastName',
		width: '6',
		required: true,
	},
	{
		type: 'text',
		label: 'Enter your street address:',
		placeholder: 'Enter your street address.',
		name: 'address1',
		width: '12',
		required: true,
	},
	{
		type: 'text',
		label: 'Enter your city:',
		placeholder: 'Enter your city.',
		name: 'city',
		width: '12',
		required: true,
	},
	{
		type: 'state',
		label: 'Enter your state/province',
		placeholder: 'Select State / Province',
		name: 'state',
		options: '',
		width: '6',
		required: true,
	},
	{
		type: 'country',
		label: 'Enter your state/province',
		placeholder: 'Select State / Province',
		name: 'state',
		options: '',
		width: '6',
		required: true,
	},
	{
		type: 'text',
		label: 'Enter your postal code',
		placeholder: 'Enter your postal code.',
		name: 'postalCode',
		width: '6',
		required: true,
	},
	{
		type: 'text',
		label: 'Enter your phone number:',
		placeholder: 'Enter your phone number.',
		name: 'phone',
		width: '6',
		required: true,
	},
	{
		type: 'email',
		label: 'Enter your email address:',
		placeholder: 'Enter your email address.',
		name: 'email',
		width: '12',
		required: true,
	},
];


module.exports.fields2 = [
	{
		type: 'text',
		label: 'Part Number:',
		placeholder: 'Enter a part number.',
		name: 'partNumber',
		width: '6',
		required: true,
	},
	{
		type: 'date',
		label: 'Date',
		name: 'date',
		width: '6',
		required: true,
	},
	{
		type: 'text',
		label: 'Serial Number:',
		placeholder: 'Enter serial number.',
		name: 'serialNumber',
		width: '6',
		required: true,
	},
];
