export const appguides = [
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%203%20IN%20SIDE%20BARS%20App%20Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['3 in round side bars'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%203%20IN%20SIDE%20BARS%20App%20Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['3 in round side bars'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%203%20IN%20PRO%20SERIES%20SIDE%20BARS%20App%20Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['3 in round side bars, pro series'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%203%20IN%20PRO%20SERIES%20SIDE%20BARS%20App%20Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['3 in round side bars, pro series'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20App%20Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['4 in oval side bars'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20App%20Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['4 in oval side bars'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20-%20W2W%20App%20Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['4 in oval side bars, wheel to wheel'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20-%20W2W%20App%20Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['4 in oval side bars, wheel to wheel'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AeroTread%20Running%20Boards%20and%20Brackets.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['5 in running boards, aerotread and mounting brackets'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AeroTread%20Running%20Boards%20and%20Brackets.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['5 in running boards, aerotread and mounting brackets'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AdvantEdge%20Side%20Bar.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['5.5 in side bars, advantedge and mounting brackets'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AdvantEdge%20Side%20Bar.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['5.5 in side bars, advantedge and mounting brackets'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%206%20IN%20OVAL%20SIDE%20BARS_MOUNTING%20BRACKETS%20App%20Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['6 in oval side bars and mounting brackets'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%206%20IN%20OVAL%20SIDE%20BARS_MOUNTING%20BRACKETS%20App%20Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['6 in oval side bars and mounting brackets'],
	},
	{
		link: 'http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Bull%20Bars.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['bull bars'],
	},
	{
		link: 'http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Bull%20Bars.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['bull bars'],
	},
	{
		link: 'http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AdvantEDGE%20Bull%20Bars.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['5.5 in bull bars, advantedge'],
	},
	{
		link: 'http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AdvantEDGE%20Bull%20Bars.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['5.5 in bull bars, advantedge'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Interiors_App_Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['styleguard floor liners'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Interiors_App_Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['styleguard floor liners'],
	},
	{
		link: 'http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Grille%20Guards.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['grille guards'],
	},
	{
		link: 'http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Grille%20Guards.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['grille guards'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Modular%20Bumper%20Data%20Tables.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['jeep accessories'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Modular%20Bumper%20Data%20Tables.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['jeep accessories'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Modular%20Bumper%20Data%20Tables.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['jeep bumper kits and replacement parts'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Modular%20Bumper%20Data%20Tables.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['jeep bumper kits and replacement parts'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20BIG%20STEP%20SIDE%20BARS%20App%20Guide.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['4 in round side bars, big step'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20BIG%20STEP%20SIDE%20BARS%20App%20Guide.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['4 in round side bars, big step'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Headache%20Racks.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['headache racks'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Headache%20Racks.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['headache racks'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AdvantEDGE%20Headache%20Racks.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['advantedge headache racks'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/AdvantEDGE%20Headache%20Racks.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['advantedge headache racks'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Jeep%20Rocker%20Steps.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['jeep rocker steps'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Jeep%20Rocker%20Steps.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['jeep rocker steps'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/RidgeStep%20Running%20Boards%20and%20Brackets.xlsx',
		type: 'xls',
		icon: 'https://storage.googleapis.com/curt-icons/Excel-Icon.png',
		cats: ['6.5 in commercial running boards, ridgestep and mounting brackets'],
	},
	{
		link: 'https://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/RidgeStep%20Running%20Boards%20and%20Brackets.pdf',
		type: 'pdf',
		icon: 'https://storage.googleapis.com/curt-icons/PDF-Icon-Aries.png',
		cats: ['6.5 in commercial running boards, ridgestep and mounting brackets'],
	},

];
