
module.exports.fields = [
	{
		type: 'text',
		label: 'Enter your first name:',
		placeholder: 'Enter your first name.',
		name: 'firstname',
		width: '6',
	},
	{
		type: 'text',
		label: 'Enter your last name:',
		placeholder: 'Enter your last name.',
		name: 'lastname',
		width: '6',
	},
	{
		type: 'text',
		label: 'Enter your email address:',
		placeholder: 'Enter your email address.',
		name: 'email',
		width: '6',
	},
	{
		type: 'text',
		label: 'Enter your phone number:',
		placeholder: 'Enter your phone number.',
		name: 'phone',
		width: '6',
	},
	{
		type: 'text',
		label: 'Enter your street address:',
		placeholder: 'Enter your street address.',
		name: 'address',
		width: '12',
	},
	{
		type: 'text',
		label: null,
		placeholder: 'Address line 2.',
		name: 'address2',
		width: '12',
	},
	{
		type: 'text',
		label: 'Enter your city:',
		placeholder: 'Enter your city.',
		name: 'city',
		width: '12',
	},
	{
		type: 'country',
		label: 'Enter your state/province',
		placeholder: 'Select State / Province',
		name: 'state',
		options: '',
		width: '6',
	},
	{
		type: 'text',
		label: 'Enter your postal code',
		placeholder: 'Enter your postal code.',
		name: 'postalcode',
		width: '6',
	},
];
