module.exports.fields = [
	{
		name: 'firstName',
		type: 'text',
		label: 'First Name:',
		placeholder: 'Enter your first name',
		required: true,
		errorMessage: 'First name is required',
		width: 6,
	}, {
		name: 'lastName',
		type: 'text',
		label: 'Last Name:',
		placeholder: 'Enter your last name',
		required: true,
		errorMessage: 'Last name is required',
		width: 6,
	}, {
		name: 'phone',
		type: 'text',
		label: 'Phone Number:',
		placeholder: 'Enter your phone number',
		required: true,
		errorMessage: 'Phone number is required',
		width: 6,
	}, {
		name: 'email',
		type: 'text',
		label: 'E-mail Address:',
		placeholder: 'Enter your e-mail address',
		required: true,
		errorMessage: 'E-mail is required',
		width: 6,
	}, {
		name: 'vehicleMake',
		type: 'text',
		label: 'Vehicle Make:',
		placeholder: 'Enter your vehicle make',
		required: false,
		width: 6,
	}, {
		name: 'vehicleModel',
		type: 'text',
		label: 'Vehicle Model:',
		placeholder: 'Enter your vehicle model',
		required: false,
		width: 6,
	}, {
		name: 'vehicleYear',
		type: 'text',
		label: 'Vehicle Year:',
		placeholder: 'Enter your vehicle year',
		required: false,
		width: 6,
	}, {
		name: 'purchaseDate',
		type: 'date',
		label: 'Date of Purchase:',
		placeholder: 'Date of purchase',
		required: true,
		width: 6,
	}, {
		name: 'purchasedFrom',
		type: 'text',
		label: 'Purchased From:',
		placeholder: 'Purchased from',
		required: false,
		width: 6,
	}, {
		name: 'dealerName',
		type: 'text',
		label: 'Dealer Name:',
		placeholder: 'Enter the dealer name',
		required: false,
		width: 6,
	}, {
		name: 'productCode',
		type: 'text',
		label: 'Product Code:',
		placeholder: 'Enter the product code',
		required: false,
		width: 6,
	}, {
		name: 'dateCode',
		type: 'text',
		label: 'Date Code:',
		placeholder: 'Enter the date code',
		required: false,
		width: 6,
	}, {
		name: 'issue',
		type: 'textarea',
		label: 'Explaine Issue:',
		placeholder: 'Please explain your issue',
		required: true,
		width: 12,
	}];
